# ==============================================================================
# Cloud Build - Auth Service (Microservicio de Autenticación)
# ==============================================================================
# Este archivo define el pipeline CI/CD para el servicio de autenticación.
# 
# Variables de sustitución requeridas (configurar en el trigger):
#   _GCP_PROJECT      - ID del proyecto GCP (ej: cafrilosa-prod)
#   _REGION           - Región de despliegue (ej: us-central1)
#   _ARTIFACT_REGISTRY - Nombre del repositorio (ej: cafrilosa-services)
#   _SERVICE_NAME     - Nombre del servicio (default: auth)
#   _DB_INSTANCE      - Conexión Cloud SQL (ej: proyecto:region:instancia)
#
# Secrets requeridos en Secret Manager:
#   - auth-jwt-secret
#   - auth-jwt-refresh-secret
#   - auth-database-url
#   - service-token-s2s
# ==============================================================================

substitutions:
  _SERVICE_NAME: 'auth'
  _ARTIFACT_REGISTRY: 'cafrilosa-services'
  _REGION: 'us-central1'

steps:
  # ==============================================================================
  # PASO 1: Construir la imagen Docker
  # ==============================================================================
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --cache-from ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest \
          .
    dir: 'aplicacion/backend/services/${_SERVICE_NAME}'

  # ==============================================================================
  # PASO 2: Subir la imagen a Artifact Registry
  # ==============================================================================
  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}'
    waitFor: ['build-image']

  # ==============================================================================
  # PASO 3: Desplegar en Cloud Run con secrets
  # ==============================================================================
  - id: 'deploy-cloudrun'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300s'
      # Variables de entorno estáticas
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=3000,ACCESS_TOKEN_TTL=12h,REFRESH_TOKEN_TTL=7d,SINGLE_SESSION=false'
      # Secrets desde Secret Manager
      - '--set-secrets'
      - 'JWT_SECRET=auth-jwt-secret:latest,JWT_REFRESH_SECRET=auth-jwt-refresh-secret:latest,DATABASE_URL=auth-database-url:latest,SERVICE_TOKEN=service-token-s2s:latest'
      # Permitir tráfico no autenticado (el servicio maneja su propia auth)
      - '--allow-unauthenticated'
    waitFor: ['push-image']

# ==============================================================================
# Configuración de imágenes y opciones
# ==============================================================================
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'