steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    dir: '.'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: '.'
images: []
options:
  machineType: "E2_HIGHCPU_8"
